---
name: "ogs-tsugi"
author: "Jonathan Strickland"

dependencies:
  - base
  - text
  - bytestring
  - transformers
  - aeson
  - servant
  - servant-client
  - servant-client-core
  - http-client-tls
  - pipes

library:
  source-dirs:
    - src

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingVia
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  
executables:
  ogs-tsugi:
    source-dirs:
      - src
    ghc-options:
      - -rtsopts
      - -g
      - -threaded
      - -main-is
      - OGS.Tsugi.Cli
    main: OGS/Tsugi/Cli.hs
